In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##Sentences 
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos arer good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos arer good']

In [11]:
##define the vocabulary size 
voc_size = 10000

In [12]:
## One hot Representation 
one_hot_repr =[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8058, 2147, 2136, 3083],
 [8058, 2147, 2136, 4584],
 [8058, 3704, 2136, 4736],
 [7102, 6364, 9512, 9951, 9587],
 [7102, 6364, 9512, 9951, 2455],
 [2341, 8058, 4983, 2136, 9249],
 [1566, 1578, 5100, 9951]]

In [13]:
## wORD embedding representation 
 
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np 


In [15]:
sent_length = 8 
embedded_doc = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 8058 2147 2136 3083]
 [   0    0    0    0 8058 2147 2136 4584]
 [   0    0    0    0 8058 3704 2136 4736]
 [   0    0    0 7102 6364 9512 9951 9587]
 [   0    0    0 7102 6364 9512 9951 2455]
 [   0    0    0 2341 8058 4983 2136 9249]
 [   0    0    0    0 1566 1578 5100 9951]]


In [16]:
## feature represenmtation 
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\saiki\OneDrive\Desktop\churn_modeling\vene\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step


array([[[-0.02673386, -0.00533969, -0.01183707,  0.03673558,
          0.0457418 ,  0.00297062, -0.03945348,  0.00112204,
         -0.01577891,  0.04846003],
        [-0.02673386, -0.00533969, -0.01183707,  0.03673558,
          0.0457418 ,  0.00297062, -0.03945348,  0.00112204,
         -0.01577891,  0.04846003],
        [-0.02673386, -0.00533969, -0.01183707,  0.03673558,
          0.0457418 ,  0.00297062, -0.03945348,  0.00112204,
         -0.01577891,  0.04846003],
        [-0.02673386, -0.00533969, -0.01183707,  0.03673558,
          0.0457418 ,  0.00297062, -0.03945348,  0.00112204,
         -0.01577891,  0.04846003],
        [ 0.02180854, -0.03458269, -0.03283848,  0.02366344,
         -0.00315142, -0.03720155,  0.03863651,  0.04989295,
         -0.04672075,  0.0104023 ],
        [-0.00334956,  0.02741322, -0.04547736,  0.04002183,
         -0.03773791,  0.048158  , -0.02877733, -0.02524861,
          0.01999456, -0.01148517],
        [-0.00966287,  0.01075228,  0.03403567, -0.0

In [20]:
embedded_doc[0]

array([   0,    0,    0,    0, 8058, 2147, 2136, 3083])